import Head from 'next/head'
import { useRouter } from 'next/router'
import { Grid } from '@mui/material'
import UniNameCard from '../../components/UniNameCard'
import MoreLink from '../../components/MorePageBtn'
import SideMenu from '../../components/Menu/SideMenu'
import PageIndicator from '../../components/PageIndicator'
import { multiData } from '../../scripts/DummyData/multi'
import { globalStyle } from '../../muiGlobalStyles/style'

export default function Index({ data, API_URL }) {
  // const router = useRouter()
  const classes = globalStyle()

  // console.log(multiData)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className={classes.root}>
        <Grid container className={classes.wrapper} spacing={0}>
          <Grid item lg={2} md={2} sm={2} xs={12}>
            <SideMenu />
          </Grid>
          <Grid item lg={10} md={10} sm={10} xs={12}>
            <PageIndicator />
            <Grid container spacing={2}>
              {data.results.map((person, index) => (
                <Grid key={person.name} item lg={6} md={6} sm={6} xs={12}>
                  <UniNameCard key={index} API_URL={API_URL} data={person} />
                </Grid>
              ))}
            </Grid>
          </Grid>
        </Grid>
        <MoreLink />
      </div>
    </div>
  )
}

export async function getServerSideProps() {
  const { API_URL } = process.env

  const res = await fetch(`${API_URL}/people`)
  const data = await res.json()

  if (!data) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }

  return {
    props: { data, API_URL },
  }
}
