import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Grid } from '@mui/material'
import UniNameCard from '../../components/UniNameCard'
import MoreLink from '../../components/MorePageBtn'
import customStyles from '../../../styles/Custom.module.css'

export default function Index({ data, API_URL }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className={` ${customStyles.pp}`}>
        <div className={` ${customStyles.centerContainer}`}>
          <div className={customStyles.centerContent}>
            <Grid container>
              {data.results.map((vehicle, index) => (
                <UniNameCard key={index} API_URL={API_URL} data={vehicle} />
              ))}
            </Grid>
            <MoreLink />
          </div>
        </div>
      </div>
    </div>
  )
}

export async function getServerSideProps() {
  const { API_URL } = process.env

  const res = await fetch(`${API_URL}/vehicles`)
  const data = await res.json()

  if (!data) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }

  return {
    props: { data, API_URL },
  }
}
